```{r}
source("preprocessing_functions.R")
library(dplyr)
library(readr)

# Generate means and sds for full population
# Load data
path <- "/mnt/Data/deidentified_data/full_cohort/preprocessed_data_long.csv"
data <- read_csv(file=path, col_names=TRUE, col_select=-1, na=c("", "NA"))

# Get only required columns
ids <- c("RandID", "visit_number",
         "date")
preds_cts = c(
  "age", # Months
  "height", # m
  "weight", # kg
  "bmi", # kg/m^2
  "fev1", # L
  "fvc", # L
  "fivc", # L 
  "fev1_fvc", # %
  "fev1_fev6", # %
  "pef", # L/s
  "mmef", # L/s
  "dlco",
  "spo2"
)
preds_bin = c("hosp_past_year", "sex") # Binary predictors
preds_categ = c("smoking_status", "mmrc") # Categorical
outcomes_bin <- c(
  "hosp_1_year", "hosp_3_year", "hosp_5_year", 
  "mort_1_year", "mort_3_year", "mort_5_year"
)

preds <- c( preds_bin, preds_cts, preds_categ)
outcomes <- c(outcomes_bin, "mort_next_time", "hosp_next_time")
data <- data %>% select(all_of(c(ids, preds, outcomes)))

data <- data %>%
  get_first_visit() %>%
  exclude_patients() %>%
  basic_preprocessing()

data <- data.frame(data)

# Convert SpO2 and age back to normal scale
data <- data %>% 
  mutate(spo2=101-exp(spo2),
         age=age*10)


head(data)

```

```{r}
# Get mean for all, male, female
data_means.all <- data %>% 
    summarise(across(all_of(preds_cts), ~mean(.x, na.rm=TRUE)))
data_sds.all <- data %>% 
    summarise(across(all_of(preds_cts), ~sd(.x, na.rm=TRUE)))
rownames(data_means.all) <- "All"
rownames(data_sds.all) <- "All1"

data_means.sex <- data %>% 
  mutate(sex = recode_factor(sex, `0`="Female", `1`="Male"))%>%
  group_by(sex) %>%
  summarise(across(all_of(preds_cts), ~mean(.x, na.rm=TRUE))) %>%
  column_to_rownames("sex")
data_sds.sex <- data %>% 
  mutate(sex = recode_factor(sex, `0`="Female1", `1`="Male1"))%>%
  group_by(sex) %>%
  summarise(across(all_of(preds_cts), ~sd(.x, na.rm=TRUE))) %>%
  column_to_rownames("sex")
data_sds.sex

data_means <- rbind(data_means.all, data_means.sex)
data_sds <- rbind(data_sds.all, data_sds.sex)
data_means <- rbind(data_means, data_sds)
colnames(data_means) <- c(
  "Age",
  "Height",
  "Weight",
  "BMI",
  "FEV_{1}",
  "FVC",
  "FIVC",
  "FEV_{1}/FVC",
  "FEV_{1}/FEV_{6}",
  "PEF",
  "MMEF",
  "DLCO",
  "SpO_{2}"     
)
data_means
```


```{r}
library(caret)
# Get count statistics for all, male, female
categ_data <- data %>%
  select(all_of(c(preds_bin, preds_categ, outcomes_bin)))

# Expand dummy variables
dummy <- dummyVars(" ~ .", data=categ_data)
newdata <- data.frame(predict(dummy, newdata = categ_data))

data_counts.all <- newdata %>% 
  mutate(n = 1, .before=1) %>%
  summarise(across(everything(), ~sum(., na.rm=TRUE)))
rownames(data_counts.all) <- c("All")
data_counts.all

# Get sex counts
sex_counts <- as.numeric(data_counts.all[,c("sex.0","sex.1")])

# Remove sex counts from all
data_counts.all <- data_counts.all %>%
  select(-sex.0, -sex.1)

data_counts.sex <- newdata %>%
  group_by(sex.0) %>%
  summarise(across(everything(), ~sum(., na.rm=TRUE))) %>%
  select(-sex.1) %>%
  mutate(n=sex_counts, .after=sex.0) %>%
  mutate(sex.0 = recode_factor(sex.0, `0`="Female", `1`="Male")) %>%
  column_to_rownames("sex.0")

data_counts <- rbind(data_counts.all, data_counts.sex) 
# Sanity check!
print(sum(data_counts[1, ] %>% as.numeric() - (data_counts[2:3,] %>% summarise(across(everything(), ~sum(.,na.rm=T))) %>%
  as.numeric())))

data_counts <- data_counts %>% select(-ends_with("FALSE"))
colnames(data_counts) <- c(
   "n",                 
   "Hospitalisation (past year)",
   "Smoking Status=0",  
   "Smoking Status=1",  
   "Smoking Status=2",  
   "mMRC=0",            
   "mMRC=1",            
   "mMRC=2",            
   "mMRC=3",
   "mMRC=4",            
   "Hospitalisation (1 years)",   
   "Hospitalisation (3 years)",   
   "Hospitalisation (5 years)",   
   "Mortality (1 years)",   
   "Mortality (3 years)",   
   "Mortality (5 years)"
)

data_pcts <- data_counts %>%
  mutate(across(everything(), ~./n))
data_counts <- rbind(data_counts, data_pcts)
```

```{r}
source("preprocessing_functions.R")
summary_statistics <- cbind(data_means, data_counts)
summary_statistics <- summary_statistics %>%
  relocate(n) %>%
  as.matrix() %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column("Variable")
ft <- summary_statistics %>%
  flextable() %>%
  mk_par(i=2:14,
         j="All",
         value=as_paragraph(fmt_avg_dev(All, All1, digit1=2, digit2=2))) %>%
  mk_par(i=15:29,
         j="All",
         value=as_paragraph(fmt_n_percent(All, All1, digit=1))) %>%
  mk_par(i=2:14,
         j="Female",
         value=as_paragraph(fmt_avg_dev(Female, Female1, digit1=2, digit2=2))) %>%
  mk_par(i=15:29,
         j="Female",
         value=as_paragraph(fmt_n_percent(Female, Female1, digit=1))) %>%
  mk_par(i=2:14,
         j="Male",
         value=as_paragraph(fmt_avg_dev(Male, Male1, digit1=2, digit2=2))) %>%
  mk_par(i=15:29,
         j="Male",
         value=as_paragraph(fmt_n_percent(Male, Male1, digit=1))) %>%
  colformat_double(i=1, digits=0) %>%
  delete_columns(j=c("All1", "Female1", "Male1"))


for (i in 1:nrow(summary_statistics)) {
  ft <- ft %>%
      compose(i = i, j = "Variable",
              value = format_sub_super_script(summary_statistics[i,"Variable"])
      )
}
ft <- ft %>%
  theme_vanilla() %>%
  autofit()

save_as_docx(ft,
             path="results/data_summary.docx")

# Need standard deviations for means data and percentages for count data
```


```{r}
# Checking distributions based on being younger or older than 80.
data %>% 
  mutate(old = age>80) %>%
  group_by(old) %>%
  summarise(num = n()/nrow(data)*100,
            num_hosp = sum(!is.na(hosp_next_time)), 
            num_mort = sum(!is.na(mort_next_time)),
            mean_hosp_time = mean(hosp_next_time, na.rm=T)/12,
            mean_mort_time = mean(mort_next_time, na.rm=T)/12)
data %>% 
  mutate(old = age>85) %>%
  group_by(old) %>%
  summarise(num = n()/nrow(data)*100,
            num_hosp = sum(!is.na(hosp_next_time)), 
            num_mort = sum(!is.na(mort_next_time)),
            mean_hosp_time = mean(hosp_next_time, na.rm=T)/12,
            mean_mort_time = mean(mort_next_time, na.rm=T)/12)


```

