```{r}
# Test for GLMNET
library(glmnet)
library(survival)
library(mice)
source("preprocessing_functions.R")

```

```{r}
library(glmnet)
library(survival)
library(mice)
source("preprocessing_functions.R")

# Load data
load("data/survival/surv_data.Rda")
load("data/survival/surv_data_imp.Rda")

preds_cts = c(
  "age", 
  "age_2",
  "height",
  "weight",
  "bmi", 
  "fev1",
  "fvc",
  "fivc",
  "fev1_fvc", 
  "fev1_fev6",
  "pef", 
  "mmef",
  "dlco",
  "spo2"
)
preds_bin = c("hosp_past_year") # Binary predictors
preds_categ = c("smoking_status.X1", "smoking_status.X2", 
                "mmrc.X1", "mmrc.X2", "mmrc.X3", "mmrc.X4") 
preds <- c(preds_cts, preds_bin, preds_categ)
npreds <- length(preds)
outcomes_surv <- c("surv_time", "status")

nimp = 10
# Create dfs
dfs <- lapply(1:nimp,
              function(i) prepare_categ_vars(
                complete(cox.imp, action=i), 
                )
              )

# Stack dfs
stacked_data <- bind_rows(dfs)

# Generate design matrices
x.female <- stacked_data %>% 
  filter(sex==0) %>%
  select(all_of(preds)) %>%
  as.matrix()
x.male <- stacked_data %>%
  filter(sex==1) %>%
  select(all_of(preds)) %>%
  as.matrix()

y.female <- stacked_data %>%
  filter(sex==0) %>%
  select(outcomes_surv) %>%
  as.matrix()
y.male <- stacked_data %>%
  filter(sex==1) %>%
  select(outcomes_surv) %>%
  as.matrix()

# Need to rename the y's
colnames(y.female) <- c("time", "status")
colnames(y.male) <- c("time", "status")

# Calculate weightings
weights.female <- (1 - rowMeans(is.na(surv.data%>%filter(sex==0))))/nimp
weights.female <- rep(weights.female, nimp)
weights.male <- (1 - rowMeans(is.na(surv.data%>%filter(sex==1))))/nimp
weights.male <- rep(weights.male, nimp)

# Generate foldids so that the same row in each imputation is in the same fold
nfolds = 5
nrow.female <- nrow(surv.data%>%filter(sex==0))
nrow.male <- nrow(surv.data%>%filter(sex==1))
foldids.female <- rep(sample(rep(1:nfolds, length.out=nrow.female)), nimp)
foldids.male <- rep(sample(rep(1:nfolds, length.out=nrow.male)), nimp)


length(foldids)
# 
# # Fit model
# fit.female <- cv.glmnet(x.female, y.female, 
#                         alpha=0.5,
#                         family="cox", type.measure="C",
#                         weights=weights.female, foldid = foldids.female)
# 
# fit.male <- cv.glmnet(x.male, y.male, 
#                       alpha = 1,
#                       family="cox", type.measure="C",
#                       weights=weights.male, foldid = foldids.male)

```

```{r}
load("models/survival/fit_female.Rda")
load("models/survival/fit_male.Rda")

library(glmnet)
library(survival)
library(mice)
source("preprocessing_functions.R")

# Load data
load("data/survival/surv_data.Rda")
load("data/survival/surv_data_imp.Rda")

preds_cts = c(
  "age", 
  "age_2",
  "height",
  "weight",
  "bmi", 
  "fev1",
  "fvc",
  "fivc",
  "fev1_fvc", 
  "fev1_fev6",
  "pef", 
  "mmef",
  "dlco",
  "spo2"
)
preds_bin = c("hosp_past_year") # Binary predictors
preds_categ = c("smoking_status.X1", "smoking_status.X2", 
                "mmrc.X1", "mmrc.X2", "mmrc.X3", "mmrc.X4") 
preds <- c(preds_cts, preds_bin, preds_categ)



npreds <- length(preds)
outcomes_surv <- c("surv_time", "status")

nimp = 100
# Create dfs
dfs <- lapply(1:nimp,
              function(i) prepare_categ_vars(
                complete(cox.imp, action=i), 
                )
              )

stacked_data <- bind_rows(dfs)
x.female <- stacked_data %>%
  filter(sex==0) %>%
  select(all_of(preds)) %>%
  as.matrix()
x.male <- stacked_data %>%
  filter(sex==1) %>%
  select(all_of(preds)) %>%
  as.matrix()

y.female <- stacked_data %>%
  filter(sex==0) %>%
  select(outcomes_surv) %>%
  as.matrix()
colnames(y.female) <- c("time", "status")
y.male <- stacked_data %>%
  filter(sex==1) %>%
  select(outcomes_surv) %>%
  as.matrix()

weights.female <- (1 - rowMeans(is.na(surv.data%>%filter(sex==0))))/nimp
weights.female <- rep(weights.female, nimp)
# fit.female$call
survival::Surv(y.female)
sf1 <- survival::survfit(fit.female, 
                         x=x.female, y=Surv(y.female[,1], y.female[,2]), 
                         weights=weights.female)
plot(sf1)
```

```{r}
y.female
y.female.surv <- Surv(y.female[,"surv_time"], y.female[,"status"])
fit.coxnet <- glmnet(x.female, y.female.surv, family="cox", alpha=0.95)
lp <- predict(fit.coxnet, newx=x.female, s=fit.female$lambda.1se, type="link")
lp
dat.test <- data.frame(y.female)
dat.test$prognosis <- ifelse(lp>0, "poor", "good")
fit.surv <- survfit(Surv(time, status) ~ prognosis,
                    data = dat.test)
ggsurvplot(fit.surv, conf.int=TRUE)

ggsurvplot(sf1, data=x.female)

install.packages("survminer")
library(survminer)
fit.female
plt.obj <- plot(sf1)


ggsurvfit(sf1)
```


```{r, fig.height=5, fig.width=5}
library(ggsurvfit)
library(svglite)
# Kaplan-Meier curve
survfit2(Surv(surv_time/12, status) ~ strata(sex),
        data = surv.data) %>%
  ggsurvfit() +
  add_confidence_interval() +
  add_risktable(risktable_stats = "{n.risk} ({cum.event})",
                stats_label = list(n.risk = "Number at Risk",
                                   cum.event = "Events")) +
  add_risktable_strata_symbol() +
  add_legend_title(c("Strata")) +
  lims(y=c(0,1)) +
  labs(x="Survival Time (years)") +
  scale_color_manual(values = c("#F8766D", "#00BFC4"),
                     labels = c("Female", "Male")) +
  scale_fill_manual(values = c("#F8766D", "#00BFC4"),
                    labels = c("Female", "Male"))
ggsave("results/survival/kaplan_meier.svg")

sf2 <- survfit2(Surv(surv_time/12, status) ~ strata(sex),
        data = surv.data)
survival_summary <- as.data.frame(summary(sf2)$table) %>%
  mutate(event.pct = events/records) %>%
  select(records, events, event.pct, median)
  
colnames(survival_summary) <- c("n", "Deaths", "Death rate (%)", "Median Survival Time (years)")
survival_summary
rownames(survival_summary) <- c("Female", "Male")
library(flextable)
library(officer)
library(tibble)
set_flextable_defaults(digits=2, decimal.mark=".")
survival_summary
ft <- flextable(survival_summary %>% rownames_to_column("Sex")) %>% 
  colformat_double(j="median", digits=2) %>%
  # colformat_int(j="events") %>%
  mk_par(j="events", 
         value = as_paragraph(fmt_n_percent(events, event.pct, digit=1))) %>%
  delete_columns("event.pct") %>%
  set_header_labels(records="n",
                    events="Deaths",
                    median="Median Survival Time (years)") %>%
  autofit() %>%
  theme_vanilla() %>%
  align(align = "center", part="header")
save_as_docx(ft, 
             path="results/survival/survival_stats.docx")

%>%
  # colformat_double(j=4:5) %>%
  # autofit() %>%
  mk_par(j="Deaths (%)",
         value=as_paragraph(events, " (", event.pct, ")")) %>%
  set_header_labels("Deaths (%)"="Deaths (%)",
                    records="N",
                    median="Median Survival Time (years)") %>% 
  autofit()

  
```

```{r}
ft %>%
  add_header_row(values=c("Sex","N", "Deaths", "Death Rate", "median surv time"))

```


```{r}
set.seed(2)
nobs <- 100; nvars <- 15
xvec <- rnorm(nobs * nvars)
xvec[sample.int(nobs * nvars, size = 0.4 * nobs * nvars)] <- 0
x <- matrix(xvec, nrow = nobs)
beta <- rnorm(nvars / 3)
fx <- x[, seq(nvars / 3)] %*% beta / 3
ty <- rexp(nobs, exp(fx))
tcens <- rbinom(n = nobs, prob = 0.3, size = 1)
y <- survival::Surv(ty, tcens)
fit1 <- glmnet(x, y, family = "cox")

# survfit object for Cox model where lambda = 0.1
sf1 <- survival::survfit(fit1, s = 0.1, x = x, y = y)
plot(sf1)
ggsurvfit(sf1)
```


```{r}
library(survival)
survfit(fit, x=x.female, y=y.female)
```


```{r}
library(mice)
library(survival)
# Imputation parameters for mice
nimp = 10
maxiter = 15
n_core = 5

pred_mat <- make.predictorMatrix(surv.data)
pred_mat[c("weight", "height"), c("bmi")] <- 0 # Remove feedback dependency
pred_mat[,c("surv_time", "status")] <- 0
pred_mat
meth <- make.method(surv.data)

```

```{r}

cox.imp <- futuremice(surv.data, n.core=n_core,
                    predictorMatrix = pred_mat, method = meth,
                    m = nimp, maxit = maxiter, print = FALSE
  )
```


```{r}
plot(cox.imp)

```
```{r}
densityplot(cox.imp)
```



```{r}
# Stack cox.imp
glmnet



```

```{r}

preprocess_survival <- function(data, preds_cts) {
  data <- data %>%
    get_first_visit() %>%
    exclude_patients() %>%
    basic_preprocessing() # No train-test splits
  preds_cts <- c(preds_cts, "decades_from_start")
  standardised_data <- standardise_variables(data, preds_cts)
  data <- standardised_data[[1]]
  data.means <- standardised_data[[2]]
  data.sds <- standardised_data[[3]]
  return(list(data, data.means, data.sds))
}

preprocess_survival(data, preds_cts)
```


```{r}
# Use GLMNET for COX regression

data("QuickStartExample")
x <- QuickStartExample$x
y <- QuickStartExample$y
```

```{r}
fit <- glmnet(x, y)
plot(fit)
```
```{r}
print(fit)
```
```{r}
# Obtain model coefficients at one or more lambdas within the range of the sequence.
coef(fit, s=0.01)
```
```{r}
set.seed(42)
nx <- matrix(rnorm(5*20), 5, 20)
predict(fit, newx = nx, s = c(0.1, 0.05))
```
```{r}
# Allow cross validation to select best lambda
cvfit <- cv.glmnet(x, y)
plot(cvfit)
```
```{r}
# Get minimum lambda
cvfit$lambda.min

```
```{r}
# Use lambda.min to get coefficients
coef(cvfit, s = "lambda.min")
```
```{r}
# Use 1 SE lambda to get coeffs
coef(cvfit, s = "lambda.1se")
# Note this is more regularised than lambda min
```
```{r}
cvfit
```

```{r}
format_sub_super_script <- function(text) {
  # Formats strings to use flextable super-sub scripting
  # See this thread for the regex magic. 
  # https://stackoverflow.com/questions/15575221/why-does-strsplit-use-positive-lookahead-and-lookbehind-assertion-matches-differ 
  
  # Split text at '^' or '_', keeping the character in the right group.
  elements <- strsplit(text, split = "(?<=.)(?=[\\^\\_])", perl = TRUE)[[1]]
  # Create empty holder for formatted elements
  formatted_elements <- list() #vector("list", length = length(elements))
  for (i in seq_along(elements)) {
    if (grepl("\\{.*\\}", elements[i], perl = TRUE)) {
      parts <- strsplit(elements[i], split="\\{|\\}", perl = TRUE)[[1]]
      if (length(parts) == 3) { # Pattern: "^{script} (extra string)"
        formatted_elements[[length(formatted_elements)+1]] <- 
          if (grepl("\\^", parts[1])) as_sup(parts[2]) else as_sub(parts[2])
        formatted_elements[[length(formatted_elements)+1]] <- parts[3]
      } else if (length(parts) == 2) { # Pattern: "^{script}"
        formatted_elements[[length(formatted_elements)+1]] <- 
          if (grepl("\\^", parts[1])) as_sup(parts[2]) else as_sub(parts[2])
      } else { # Should not get here
        print(paste("ERROR:", elements[i], "contains weird pattern")) 
        formatted_elements[[length(formatted_elements)+1]] <- elements[i]
      }
    } else { # Element does not contain subscript or superscript
      formatted_elements[[length(formatted_elements)+1]] <- elements[i]
    }
  }
  # return(as_paragraph(unlist(formatted_elements), sep=""))
  return(as_paragraph(list_values=formatted_elements))
}
```


```{r}

library(tibble)
library(glmnet)
library(survival)
library(mice)
library(flextable)
library(officer)
source("preprocessing_functions.R")

# Load data
load("data/survival/surv_data.Rda")
load("data/survival/surv_data_imp.Rda")

create_coef_table <- function(operating_point) {
  load("models/survival/fit_female.Rda")
  load("models/survival/fit_male.Rda")

  preds_cts = c(
    "age", 
    "age_2",
    "height",
    "weight",
    "bmi", 
    "fev1",
    "fvc",
    "fivc",
    "fev1_fvc", 
    "fev1_fev6",
    "pef", 
    "mmef",
    "dlco",
    "spo2"
  )
  preds_bin = c("hosp_past_year") # Binary predictors
  preds_categ = c("smoking_status.X1", "smoking_status.X2", 
                  "mmrc.X1", "mmrc.X2", "mmrc.X3", "mmrc.X4") 
  preds <- c(preds_cts, preds_bin, preds_categ)
  
  if(operating_point == "min") {
    coef.female <- coef(fit.female, s=fit.female$lambda.min)
    coef.male <- coef(fit.male, s=fit.male$lambda.min)
  } else if(operating_point == "1se") {
    coef.female <- coef(fit.female, s=fit.female$lambda.1se)
    coef.male <- coef(fit.male, s=fit.male$lambda.1se)
  }
  coef.df <- as.data.frame(as.matrix(cbind(coef.female, coef.male)))
  
  colnames(coef.df) <- c("Female", "Male")
  # Save coefficient data
  save(coef.df, 
       file=paste("results/survival/coefs_", 
                  operating_point, ".Rda", sep=""))
  
  # Prepare coefs for being in a word document:
  coef.df <- coef.df %>% 
    # Transpose
    t() %>% 
    as.data.frame() %>%
    # group mmrc and smoking status
    group_mmrc() %>% 
    group_smoking_status() %>% 
    t() %>% 
    as.data.frame() 
  # Define rownames
  rownames(coef.df) <- c(
    "Age",
    "Age^{2}",
    "Height",
    "Weight",
    "BMI",
    "FEV_{1}",
    "FVC",
    "FIVC",
    "FEV_{1}/FVC",
    "FEV_{1}/FEV_{6}",
    "PEF",
    "MMEF",
    "DLCO",
    "SpO^{2}",
    "Hospitalisation (Past Year)",
    "mMRC=1",
    "mMRC=2",
    "mMRC=3",
    "mMRC=4",
    "Smoking Status=Ex",
    "Smoking Status=Current"
  )
  coef.df <- coef.df %>% 
    rownames_to_column("Variable")
  coef.df
  ft <- flextable(coef.df)
  for (i in 1:nrow(coef.df)) {
    ft <- ft %>%
      compose(i = i, j = "Variable",
              value = format_sub_super_script(coef.df[i,"Variable"])
      )
  }
  
  # Automaticall make cells not zero bold.
  bold_points <- which(coef.df[,2:ncol(coef.df)] != 0, arr.ind=TRUE)
  bold_points[,"col"] <- bold_points[,"col"] +1
  for (row in 1:nrow(bold_points)) {
    ft <- ft %>%
      bold(i=bold_points[row,"row"],
           j=bold_points[row,"col"])
  }
  ft
  ft <- ft %>%
  ft %>%
    colformat_double(digits=3) %>%
    # theme_vanilla() %>%
    # bold(i=~Female!=0, j="Female") %>%
    # bold(i=bold_points[,"row"], j=bold_points["col"]) %>%
    bold(i=c(1,2), j=c(2,3))
    bold(part="header") %>%
    set_table_properties(width=0.5) %>%
    # align(align = "center", part="all") %>%
    autofit()
  ft
  save_as_docx(ft, 
               path=paste("results/survival/coefs_", 
                          operating_point, ".docx", sep=""))
}

create_coef_table(operating_point="min")
create_coef_table(operating_point="1se")
operating_point <- "min"
```








